# Generated by Django 5.0.6 on 2024-07-28 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0004_alter_accountuser_account_user_id_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('11238b7f-eee4-4612-9291-80da711812da'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendcourse',
            name='attendcourse_id',
            field=models.UUIDField(default=uuid.UUID('6b9e6c2e-7bd6-4643-ae56-bef4770d6361'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('c0c511bd-4f57-4bb7-81f1-b340f32dc2fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
