# Generated by Django 5.0.6 on 2024-07-28 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0005_alter_accountuser_account_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('87d63fd9-6105-4cd4-a520-dccf693f55c2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendcourse',
            name='attendcourse_id',
            field=models.UUIDField(default=uuid.UUID('c7dcb70a-45ff-4872-9020-52bbca31512b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('0c8d630a-dc0e-4095-837c-970882d2af84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
