# Generated by Django 5.0.6 on 2024-07-28 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0006_alter_accountuser_account_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('64042333-6be3-4f9d-a5c4-6be4813202d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendcourse',
            name='attendcourse_id',
            field=models.UUIDField(default=uuid.UUID('1fea0fc5-e3e4-4eca-9f98-f72ee382041c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('703c9cb8-f8ce-4026-94d0-6222bbe71b7d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
