# Generated by Django 5.0.6 on 2024-07-28 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0007_alter_accountuser_account_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('5dd9c9ac-ff47-4638-a86d-243e458c6db2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='attendcourse',
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
