# Generated by Django 5.0.6 on 2024-07-28 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0008_alter_accountuser_account_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('c8708072-08cf-48e5-b662-88055a2157a6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
