# Generated by Django 5.0.6 on 2024-07-28 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0009_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('75fa6bf4-cd3a-4773-bb65-18d0e8487bc5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
