# Generated by Django 5.0.6 on 2024-06-19 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountuser',
            new_name='pandih_acco_account_5b97e1_idx',
            old_name='pandih_acco_account_11c995_idx',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('b9b4aebf-d8a3-40cd-98b6-2862bf35224a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
