# Generated by Django 5.0.6 on 2024-06-28 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandih', '0003_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('bf3555d8-3693-4c18-bd5d-b983ec219eed'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.UUID('c390bb71-48ba-4d85-83ab-c15a7b0a1741'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(editable=False, max_length=255)),
                ('course_created_by', models.CharField(max_length=255)),
                ('course_created_date', models.DateTimeField(auto_now_add=True)),
                ('course_updated_by', models.CharField(max_length=255, null=True)),
                ('course_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('course_id',),
                'indexes': [models.Index(fields=['course_id'], name='pandih_cour_course__ef77e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='attendcourse',
            fields=[
                ('attendcourse_id', models.UUIDField(default=uuid.UUID('f8bc9825-84be-4653-a421-1129523384f3'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('attendcourse_accountprofileid', models.CharField(max_length=255)),
                ('attendcourse_created_by', models.CharField(max_length=255)),
                ('attendcourse_created_date', models.DateTimeField(auto_now_add=True)),
                ('attendcourse_updated_by', models.CharField(max_length=255, null=True)),
                ('attendcourse_updated_date', models.DateTimeField(auto_now_add=True)),
                ('attendcourseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandih.course')),
            ],
            options={
                'ordering': ('attendcourse_id',),
                'indexes': [models.Index(fields=['attendcourse_id', 'attendcourse_id'], name='pandih_atte_attendc_c33dd5_idx')],
            },
        ),
    ]
